# Generated by Django 6.0.4 on 2026-04-29 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookiesession",
            name="context",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="cookiesession",
            name="id",
            field=models.CharField(
                max_length=40, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("context", models.JSONField(default=list)),
                (
                    "cookie_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="cbot.cookiesession",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cookiesession",
            name="current_chat_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cbot.chatsession",
            ),
        ),
        migrations.DeleteModel(
            name="Session",
        ),
    ]
