# Generated by Django 6.0.4 on 2026-05-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbot", "0002_alter_cookiesession_context_alter_cookiesession_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, unique=True)),
                ("contents", models.JSONField(default=list, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="chatsession",
            name="reference_doc_index",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cookiesession",
            name="docs_used_indices",
            field=models.JSONField(default=list),
        ),
    ]
