# Generated by Django 6.0.4 on 2026-05-04 00:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbot", "0003_document_chatsession_reference_doc_index_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="reference_doc_index",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cookiesession",
            name="reference_doc_index",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cookiesession",
            name="docs_used_indices",
            field=models.JSONField(default=list),
        ),
    ]
