# Generated by Django 6.0.4 on 2026-05-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbot", "0004_remove_chatsession_reference_doc_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookiesession",
            name="docs_used_indices",
            field=models.JSONField(default=list),
        ),
    ]
