# Generated by Django 6.0.4 on 2026-05-04 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbot", "0005_alter_cookiesession_docs_used_indices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cookiesession",
            name="docs_used_indices",
        ),
        migrations.RemoveField(
            model_name="cookiesession",
            name="reference_doc_index",
        ),
        migrations.AddField(
            model_name="cookiesession",
            name="current_chunk_index_of_reference_doc",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cookiesession",
            name="reference_doc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rd",
                to="cbot.document",
            ),
        ),
        migrations.AddField(
            model_name="cookiesession",
            name="used_chunks_indices",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="cookiesession",
            name="current_chat_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cs",
                to="cbot.chatsession",
            ),
        ),
    ]
