# Generated by Django 6.0.4 on 2026-05-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbot", "0006_remove_cookiesession_docs_used_indices_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookiesession",
            name="used_chunks_indices",
            field=models.JSONField(default=list),
        ),
    ]
