# Generated by Django 6.0.4 on 2026-05-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbot', '0007_alter_cookiesession_used_chunks_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiesession',
            name='is_compressing_context',
            field=models.BooleanField(default=False),
        ),
    ]
