# Generated by Django 6.0.4 on 2026-05-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbot', '0008_cookiesession_is_compressing_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiesession',
            name='use_plain_font',
            field=models.BooleanField(default=False),
        ),
    ]
